services:
  ntp2038:
    image: ichikawayukko/ntp2038
    build:
      context: .
    # You can specify the year of NTP server here.
    # default:
    #   OFFSET_YEAR: differense from 2038
    #   OFFSET_DAYS: 3 (Leap year 2028, 2032, 2036)
    #   SERVER:      pool.ntp.org
    #environment:
    #  - OFFSET_YEAR=13
    #  - OFFSET_DAYS=3
    #  - SERVER=pool.ntp.org
    container_name: ntp2038
    restart: on-failure:10
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/ptp0:/dev/ptp0"
      - "/dev/ptp1:/dev/ptp1"
      - "/dev/ptp2:/dev/ptp2"
      - "/dev/ptp3:/dev/ptp3"
    network_mode: host

