services:
  ntp2038:
    image: ichikawayukko/ntp2038
    build:
      context: .
    ports:
      - "123:123/udp"
    # You can specify the year of NTP server here.
    # default: 2038
    #environment:
    #  - NTP_YEAR=2022
    container_name: ntp2038
    restart: always

